name: Pull request checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  commit-message-check:
    name: Block fixup and squash commits

    runs-on: ubuntu-latest

    steps:
      - name: Run check
        uses: skjnldsv/block-fixup-merge-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
