name: Lint

on: pull_request

permissions:
  contents: read

concurrency: 
  group: eslint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest

    name: eslint
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@8205673bab74a63eb9b8093402fd9e0e018663a1 # v2.2
        id: versions
        with:
          fallbackNode: '^20'
          fallbackNpm: '^10'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
